name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted
    defaults:
      run:
        working-directory: .

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Build with hugo
      run: hugo
    - name: Install dependencies
      run: cd scripts && yarn
    - name: Upload to swarm
      run: cd scripts && node upload-blog-to-swarm.js > upload-out.txt
      env:
        CI: false
